name: Devops github actions parcial

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install -g surge
      
      - name: review secret
        run: echo ${{ secrets.SURGE_TOKEN }}

      - shell: bash
        run: surge --token 3201c9d67019829e5d5613c8f42ace65 --project ../../ --domain devops-practice-heger-mel.surge.sh
        