name: Devops github actions parcial

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: surge --token ${{ secrets.SURGE_TOKEN }} --project ../../ --domain devops-practice-heger-mel.surge.sh
        