name: Devops github actions parcial

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install -g surge
      
      - name: review secret
        run: echo ${{ secrets.SURGE_TOKEN }}

      - name: Deploy to Surge
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SURGE_TOKEN }}
        run: |
          surge --token "$SUPER_SECRET" --project ../../ --domain devops-practice-heger-mel.surge.sh
        